services:
  - type: web
    name: harper-ai-website
    env: static
    buildCommand: echo "Static site, no build needed"
    staticPublishPath: ./user-workspace
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
