services:
  - type: static
    name: mohit-ai-website
    buildCommand: docker build --build-arg CACHE_BUST=$(date +%s) -t mohit-ai-website .
    publishDir: user-workspace
    staticPublishPath: /
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
