services:
  - type: static
    name: mohit-ai-website
    buildCommand: echo "Static site, rebuilding $(date)"
    publishDir: user-workspace
    staticPublishPath: /
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
